use_frameworks!

platform :ios, '10.0'

target 'likeminds-feed-iOS_Example' do
  pod 'likeminds-feed-iOS', :path => '../'

  target 'likeminds-feed-iOS_Tests' do
    inherit! :search_paths

    
  end
end
