# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '13.0'

workspace 'lm-feed-video-sample-app.xcworkspace'

target 'lm-feed-video-sample-app' do
  project 'lm-feed-video-sample-app.xcodeproj'
  use_frameworks!
 
  pod 'LikeMindsFeed', path:'../../likeminds-feed-ios-data/LikeMindsFeedDev.podspec'
  pod 'LikeMindsFeedUI', path: '../LikeMindsFeedUI.podspec'
  pod 'LikeMindsFeedCore', path: '../LikemindsFeedCore.podspec'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
