# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

workspace 'lm-feed-sample-app.xcworkspace'

target 'lm-feed-sample-app' do
  project 'lm-feed-sample-app.xcodeproj'
  use_frameworks!
  
  pod 'LikeMindsFeed', path: '/Users/devanshmohata/Desktop/WORK/Feed/LikeMinds-iOS-Feed-SDK/LikeMindsFeed.podspec'
  pod 'LikeMindsFeedUI', path: '../LikeMindsFeedUI.podspec'
  pod 'LikeMindsFeedCore', path: '../LikeMindsFeedCore.podspec'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
