name: Create Git Tag and Git Release

on:
    push:
        branches: master
    
permissions: write-all

jobs:
    create_tag:
        name: Create Git Tag
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            
            - name: Push Git Tag
              run: |
                # Git login
                git config --global user.name "$(git log -n 1 --pretty=format:%an)"
                git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
        
                # Push a Git tag with the new version
                export current_version=$(grep 'spec.version' LikeMindsFeedCore.podspec | awk -F '"' '/spec.version/{print $2}' | tr -d '\n' | sed 's/[^0-9.]//g; s/\..$//')
                git tag -a "v$current_version" -m "Version $current_version"
                git push origin "v$current_version"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    create-github-release:
        name: Create Github Release
        runs-on: ubuntu-latest
        needs: create_tag
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            
            - name: Create Release
              run: gh release create "$(git describe --tags --abbrev=0)" --generate-notes
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}